# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - facets-journal

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY_LOGIN_SERVER: ${{ vars.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER_DEV }}
  AZURE_CONTAINER_REGISTRY_USERNAME: ${{ vars.AZURE_CONTAINER_REGISTRY_USERNAME_DEV }}
  AZURE_CONTAINER_REGISTRY_PASSWORD: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD_DEV }}
  AZURE_GITHUB_SERVICE_PRINCIPLE: ${{ secrets.AZURE_GITHUB_SERVICE_PRINCIPLE_DEV }}

  NODE_VERSION: '18'
  REGISTRY_FOLDER: journal
  PORT: 8080
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  VITE_OPENAI_API_KEY: ${{ secrets.VITE_OPENAI_API_KEY }}
  VITE_TINY_MCE_KEY: ${{ secrets.VITE_TINY_MCE_KEY }}

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_GITHUB_SERVICE_PRINCIPLE }}

      - name: Login to Docker Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}
          username: ${{ env.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ env.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image (Development)
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.REGISTRY_FOLDER }}:${{ github.sha }} -f Dockerfile . \
          --build-arg DATABASE_URL="${{ env.DATABASE_URL }}" \
          --build-arg VITE_OPENAI_API_KEY="${{ env.VITE_OPENAI_API_KEY }}" \
          --build-arg VITE_TINY_MCE_KEY="${{ env.VITE_TINY_MCE_KEY }}" \
          --build-arg PORT="${{ env.PORT }}"
          docker push ${{ env.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.REGISTRY_FOLDER }}:${{ github.sha }}

          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.REGISTRY_FOLDER }}:latest -f Dockerfile . \
          --build-arg DATABASE_URL="${{ env.DATABASE_URL }}" \
          --build-arg VITE_OPENAI_API_KEY="${{ env.VITE_OPENAI_API_KEY }}" \
          --build-arg VITE_TINY_MCE_KEY="${{ env.VITE_TINY_MCE_KEY }}" \
          --build-arg PORT="${{ env.PORT }}"
          docker push ${{ env.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.REGISTRY_FOLDER }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    # steps:
    #   - name: Download artifact from build job
    #     uses: actions/download-artifact@v3
    #     with:
    #       name: node-app

    #   - name: Unzip artifact for deployment
    #     run: unzip release.zip

    #   - name: 'Deploy to Azure Web App'
    #     id: deploy-to-webapp
    #     uses: azure/webapps-deploy@v2
    #     with:
    #       app-name: 'facets-journal'
    #       slot-name: 'Production'
    #       publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CE58440F228442C7B0E3E3E6A6829941 }}
    #       package: .

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_GITHUB_SERVICE_PRINCIPLE }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}
          username: ${{ env.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ env.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'facets-journal'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CE58440F228442C7B0E3E3E6A6829941 }}
          images: '${{ env.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.REGISTRY_FOLDER }}:${{ github.sha }}'
